'use strict';

const ISSUE_TYPES = ['DEFECT', 'IMPROVEMENT', 'INQUIRY'];
const ISSUE_PREFIX = { DEFECT: 'DEF', IMPROVEMENT: 'IMP', INQUIRY: 'INQ' };
const PREFIX_TYPE = { DEF: 'DEFECT', IMP: 'IMPROVEMENT', INQ: 'INQUIRY' };

const STATUS = {
  DRAFT: 'DRAFT',
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  DONE: 'DONE',
  CLOSED: 'CLOSED',
  CANCEL: 'CANCEL',
};
const ISSUE_STATUSES = Object.values(STATUS);

const PRIORITY = { CRITICAL: 'CRITICAL', MAJOR: 'MAJOR', MINOR: 'MINOR', UNASSIGNED: 'UNASSIGNED' };
const PRIORITIES = Object.values(PRIORITY);

const CLOSE_TYPES = ['VERIFIED', 'AGREED'];
const DEPLOYMENT_STATUS = { NOT_DEPLOYED: 'NOT_DEPLOYED', DEPLOYED: 'DEPLOYED' };

const EVENT = {
  CREATED: 'CREATED',
  UPDATED: 'UPDATED',
  COMMENTED: 'COMMENTED',
  COMMENT_HIDDEN: 'COMMENT_HIDDEN',
  ASSIGNED: 'ASSIGNED',
  PRIORITY_CHANGED: 'PRIORITY_CHANGED',
  STATUS_CHANGED: 'STATUS_CHANGED',
  RESOLVED: 'RESOLVED',
  RESOLUTION_EDITED: 'RESOLUTION_EDITED',
  DEPLOYED: 'DEPLOYED',
  REOPENED: 'REOPENED',
  CANCELLED: 'CANCELLED',
  CLOSED: 'CLOSED',
  ADMIN_STATUS_OVERRIDE: 'ADMIN_STATUS_OVERRIDE',
  ATTACHMENT_ADDED: 'ATTACHMENT_ADDED',
  ATTACHMENT_DELETED: 'ATTACHMENT_DELETED',
  ISSUE_DELETED: 'ISSUE_DELETED',
  USER_DELETED: 'USER_DELETED',
};

/** Workflow Action별 허용 from → to (06_WORKFLOW §4) */
const TRANSITIONS = {
  submit: { from: [STATUS.DRAFT], to: STATUS.OPEN },
  start: { from: [STATUS.OPEN], to: STATUS.IN_PROGRESS },
  resolve: { from: [STATUS.IN_PROGRESS], to: STATUS.DONE },
  reopen: { from: [STATUS.DONE, STATUS.CLOSED], to: STATUS.IN_PROGRESS },
  close: { from: [STATUS.DONE], to: STATUS.CLOSED },
  cancel: { from: [STATUS.OPEN, STATUS.IN_PROGRESS, STATUS.DONE], to: STATUS.CANCEL },
};

/** Reporter가 수정 가능한 등록내용 Field allowlist */
const EDITABLE_FIELDS = {
  DEFECT: ['location', 'environmentId', 'symptom', 'reproductionSteps', 'expectedResult'],
  IMPROVEMENT: ['target', 'request', 'reason'],
  INQUIRY: ['target', 'question'],
};

module.exports = {
  ISSUE_TYPES,
  ISSUE_PREFIX,
  PREFIX_TYPE,
  STATUS,
  ISSUE_STATUSES,
  PRIORITY,
  PRIORITIES,
  CLOSE_TYPES,
  DEPLOYMENT_STATUS,
  EVENT,
  TRANSITIONS,
  EDITABLE_FIELDS,
};
